apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-config
data:
  SPRING_PROFILES_ACTIVE: mysql
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/accountsdb?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root