apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # Values must be base64 encoded
  # To encode: echo -n 'root' | base64   (gives 'cm9vdA==')
  MYSQL_ROOT_PASSWORD: cm9vdA==  # Base64 encoded 'root'